name: build
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: make -j build/linux build/windows
      - name: Upload
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          name: coder-cli
          path: ./ci/bin/coder-cli-*

  build_darwin_pull:
    runs-on: macos-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: unset CI && make build/macos

  build_darwin_master:
    runs-on: macos-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Gon
        run: |
          brew tap mitchellh/gon
          brew install mitchellh/gon/gon

      - name: Import Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_BASE64 }}
          p12-password: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}

      - name: Build master
        run: make build/macos
        env:
          AC_USERNAME: ${{ secrets.AC_USERNAME }}
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: coder-cli
          path: ./ci/bin/coder-cli-*
