name: build

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: ./ci/steps/build.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: coder-cli
          path: ./ci/bin/coder-cli-*
