name: build
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.6' # The Go version to download (if necessary) and use.
      # - name: Install Gon
      #   run: |
      #     brew tap mitchellh/gon
      #     brew install mitchellh/gon/gon
      # - name: Import Signing Certificates
      #   uses: Apple-Actions/import-codesign-certs@v1
      #   with:
      #     p12-file-base64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_BASE64 }}
      #     p12-password: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}
      - name: Build
        # run: ./ci/steps/build.sh
        run: |
          go build -ldflags "-X cdr.dev/coder-cli/internal/version.Version=vdean" -o ./ci/bin/coder-cli-windows.exe ./cmd/coder
        env:
          AC_USERNAME: ${{ secrets.AC_USERNAME }}
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
          GOOS: windows
          GOARCH: '386'
          CGO_ENABLED: '0'
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: coder-cli
          path: ./ci/bin/coder-cli-*
