name: ci
on: [push, pull_request]

jobs:
  integration:
    runs-on: ubuntu-latest
    env:
      CODER_URL: ${{ secrets.CODER_URL }}
      CODER_EMAIL: ${{ secrets.CODER_EMAIL }}
      CODER_PASSWORD: ${{ secrets.CODER_PASSWORD }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14'
      - name: go test
        run: go test ./ci/integration/...
